# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
name: Node.js CI

# name: Do things at 10:00 and 22:00 every day UTC
#on: push
on:
  schedule:
  - cron: "00 22,10 * * *"
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name nach131
        git config user.email nacho.mota@gmail.com
        git add .
        git commit -m "generated"
        git push
